{
  "version": 1,
  "status": "fail",
  "message": "\u001b[0;31mF\u001b[0m\u001b[0;31mF\u001b[0m\nFailures:\n\n  1) all_fail_test:one_test/0\n\u001b[0;31m     Failure: ?assertEqual(<<111,111,112,115>>, Actual)\n       expected: <<\"oops\">>\n            got: <<\"one\">>\u001b[0m\n\u001b[0;36m     %% eunit_proc.erl:346:in `eunit_proc:with_timeout/3`\u001b[0m\n\u001b[0;36m     Output: \u001b[0m\n\u001b[0;36m     Output: \u001b[0m\n\n  2) all_fail_test:two_test/0\n\u001b[0;31m     Failure: ?assertEqual(<<111,111,112,115>>, Actual)\n       expected: <<\"oops\">>\n            got: <<\"two\">>\u001b[0m\n\u001b[0;36m     %% eunit_proc.erl:346:in `eunit_proc:with_timeout/3`\u001b[0m\n\u001b[0;36m     Output: \u001b[0m\n\u001b[0;36m     Output: \u001b[0m\n\n\u001b[0;31m2 tests, 2 failures\n\u001b[0m"
}
